### ISSUE TITLE
Cannot connect to Nextcloud

### ISSUE THREAD

**Issue by orsomannaro** [schaal/ocreader#71]
Nextcloud 12
Android 5.1.1

Trying to connect to this URL (and some others sub paths...):

_https://my.domain.com/nextcloud_

I have this error:

_Nextcloud News not installed or version not supported. Please install or update to at least %s_

What I'm doing wrong?

Thanks.

**Comment by schaal** [comment]
Is it possible for you to include the logcat output?

**Comment by NetSoerfer** [comment]
I'm having the same problem, possibly since updating to Nextcloud 12.

In my instance it's caused by an invalid certificate CN. 

I've been using my signed 'public' cert for my local LAN too, even though it doesn't match the local hostnames. The following used to work, but is now causing the error message described by the OP:

The certificate is valid for *.mydomain.net and mydomain.net.
My local DNS suffix is .lan.mydomain.net, resulting in hostnames such as hostname.lan.mydomain.net, which is not covered by the certificate (since wildcards don't cover multiple domain levels).

Don't know if this is the cause of the OP's problem, but the above was pretty obvious from my logcat. The error message is pretty confusing :)

**Comment by Gildas-GH** [comment]
Hi,
Try to add a / at the end of the adress, like

https://my.domain.com/nextcloud**/**
Or https://my.domain.com**/**

I had this issue on Nextcloud Notes some time ago, I think it's the same problem

Merry Christmas ;)

**Comment by filipesaraiva** [comment]
I am having the same problem. Maybe it is related to invalid certified as @NetSoerfer pointed because it is the same for me (I am using a shared host).

**Comment by daald** [comment]
Having the same problem.

nextcloud is a docker installation, there I see these logs

```
db_1   | 2019-11-18 01:14:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server  started.
db_1   | 2019-11-18 01:14:04+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1   | 2019-11-18 01:14:05+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server  started.
db_1   | 2019-11-18 01:14:05+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
db_1   | 	You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD

```

but everything on the UI works. 

At installation time, the setup told me I'm not using maria/mysql at all ("You chose SQLite as database.")

**Comment by schaal** [comment]
Unfortunately self-signed certificates are not supported right now (tracked in bug #91)
