### ISSUE TITLE
"unread" status is not synced properly

### ISSUE THREAD

**Issue by tobiasKaminsky** [schaal/ocreader#85]
## Description of the issue
As I have many feeds, I set up a script, which marks all unread items that are older than 7 days as read. 
On web ui therefore I only have articles from within the last 7 days, when showing only unread items.

## Expected behavior
Same should be visible on this app.
Currently I have e.g. 
ProLinuxNews 29, but should be 8
Heise dev 127, but should be 11

I am not sure if I am on the right track, but in 
https://github.com/tobiasKaminsky/ocreader/blob/40fd40c23189d3f51058e0de35f390bb69f14ff8/app/src/main/java/email/schaal/ocreader/api/APIv12.java#L328

you are using the last sync date, which then leads to changes to items that are newer than this date.
This is more a "sync only changes"?
A full sync should also refresh the old stored items, or? 

If you point me to the right direction, and if it is possible to fix, I am glad to help.

Thank you for this great app. 
It is my # 1 app on android :+1:

**Comment by schaal** [comment]
> you are using the last sync date, which then leads to changes to items that are newer than this date.
This is more a "sync only changes"?

If provided with the last sync date, the server sends back all items that were changed since the last sync, this means all articles should be updated to reflect their new status.

> A full sync should also refresh the old stored items, or?

Yes, but a full sync is only done when the database is empty, i.e. only the first time or when it was reset.

If the items aren't in sync with the server, there must be a bug somewhere. I'll look into it.

> Thank you for this great app.
> It is my # 1 app on android +1

Thanks, that's great to hear!

**Comment by towo** [comment]
Bump for this. Server reads don't seem to sync successfully.

**Comment by schaal** [comment]
The sync backend was rewritten in version 0.45, so if this is still an issue please reopen this bug.

There is now also an option to reset the database, which will redownload all unread articles.
