### ISSUE TITLE
Sometimes blank article view

### ISSUE THREAD

**Issue by mase76** [schaal/ocreader#9]
Some articles of https://blog.fefe.de and all articles of https://netzpolitik.org show a blank article view. Touching the emptiness opens the correct article in the webbrowser.

**Comment by schaal** [comment]
This might already be fixed by 6b1d39be301504c5a2e8e8567cb6ecebbed616b5. Previously the webview had to render the whole page at once, which can exceed the graphics memory limit and lead to such issues, after this commit it only renders the portion of the page in view.

I'll try to get a new release out soon.

**Comment by schaal** [comment]
Does this still occur with version 0.12?

**Comment by mase76** [comment]
Seems to be solved now.
